# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SamAnalytics  
email: samantha.jane.macd@gmail.com 
description: "A novice data science blog." 
baseurl: "" # the name of the repository 
url: "https://samanthamacd.github.io" #  change this to "https://<your-github-username>.github.io"
image: "/assets/image/maxim-berg-kE8-rUKjtQU-unsplash.jpg" 
author: Samantha MacDonald 
copyright: SJM # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 'The default image for the site header is a random image from 
        <a href="https://source.unsplash.com/random" target="_blank"> Unsplash</a>. 
        The default image for the blog post is from
        <a href="https://unsplash.com/photos/DWpR-BpKlw0?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink" target="_blank"
        >Unsplash by Mohamed Elsayed</a>. Students in Stat 386 using this theme should replace both images 
        with their own.'


# Social media users names.  Leave fields blank that you don't want displayed

github_username: samanthamacd

plugins:
  - jekyll-feed

